drop table Person;
create table Person
(
    id    int8 generated by default as identity primary key, /*GENERATED BY DEFAULT AS IDENTITY (В Oracle также - стандарты SQL)*/
    name  varchar(30) not null,
    age   int4        not null check ( age > 0 ),
    email varchar(30) not null unique
);

insert into Person (name, age, email)
VALUES ('Tom', 23, 'tom@mail.ru'),
       ('Bob', 55, 'bob@mail.ru'),
       ('John', 36, 'john@mail.ru');

insert into Person (name, age, email)
VALUES ('Peter', 15, 'peter@gmail.com');

select *
from Person;