drop table Person;
create table Person
(
    id      int8 generated by default as identity primary key, /*GENERATED BY DEFAULT AS IDENTITY (В Oracle также - стандарты SQL)*/
    name    varchar(30)  not null,
    age     int4         not null check ( age > 0 ),
    email   varchar(30)  not null unique,
    address varchar(100) not null
);

--alter table Person add column address varchar(100) not null default '';

insert into Person (name, age, email, address)
VALUES ('Tom', 23, 'tom@mail.ru', 'USA, Los-Angeles, 054200'),
       ('Bob', 55, 'bob@mail.ru', 'USA, Boston, 541826'),
       ('John', 36, 'john@mail.ru', 'USA, Florida, 496002');

select * from Person;